// Display names for subject codes. Edit freely.
export const SUBJECT_NAMES = {
  AC: "Accounting",
  AF: "Afrikaans",
  BS: "Business Studies",
  CAT: "CAT",
  DA: "Dance",
  DR: "Drama",
  ED: "EGD",
  EMS: "EMS",
  EN: "English",
  FR: "French",
  FSE: "FS English",
  FSM: "FS Maths",
  FSS: "FS Science",
  GE: "Geography",
  HI: "History",
  IT: "IT",
  LO: "Life Orientation",
  LS: "Life Sciences",
  MA: "Mathematics",
  MANDARIN: "Mandarin",
  ML: "Maths Lit",
  MU: "Music",
  OA: "Art",
  OD: "Drama",
  ODA: "Dance",
  OE: "EGD",
  OF: "French",
  OM: "Music",
  PE: "Phys Ed",
  RDI: "RDI",
  S: "S",
  SC: "Natural Sciences",
  ST: "Study",
  TE: "Technology",
  V: "V",
  VA: "Visual Arts",
  ZU: "isiZulu",
};

export function subjectDisplay(code) {
  return SUBJECT_NAMES[code] ?? code;
}
